application: victor-com-ng
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|json|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|json|css))

- url: /(.*\.(svg|svgz))
  static_files: \1
  upload: (.*\.(svg|svgz))
  http_headers:
    content-type: image/svg+xml

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: \1
  upload: (.*\.ttf)

- url: /(.*\.xml)
  static_files: \1
  upload: (.*\.xml)

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /static
  static_dir: static
  application_readable: true

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"
